### ISSUE TITLE
Viewer application crashing

### ISSUE THREAD

**Issue by akash901** [OpenNuvoton/ToF-viewer-app-for-Qualcomm-RB5#1]
Hello @navnunni @keanheong ,
 Thank you for pushing Tof camera viewer application with Qualcomm RB5 development board. 

We had purchased RB5 vision kit from thundercomm and flashed thundercomm LU image on board. While trying out Tof viewer application we are experiencing crash on all our boards. Attaching crash log for your reference. Please help us to debug this further.

Also Is there any ROS driver available for this ToF camera from Nuvoton which can work on RB5?

`
root@qrb5165-rb5:~/ros_ws/pallav_ws/src/ToF-viewer-app-for-Qualcom./build/viewer 

----------------------------------------
Viewer [ver0001]

Ranging mode selection 
0 : MODE0
1 : MODE1
Your choice : 1

tl_dev_open: line:654 

Number of camera:3
0: facing:1, orien:270, version:773, cost:100, conflict_length:0
1: facing:2, orien:270, version:773, cost:100, conflict_length:0
2: facing:1, orien:180, version:773, cost:100, conflict_length:0(TOF)
tl_dev_eeprom_read_cmn_mode: new p_cmn_mode:0x55906a0010, size:2160 E

mod_name:PANASONIC TOF CAMERA, afe_name:ADDI9043, sns_name:MN34906, lns_name:J6920
map_ver:0x3102, sno_u:0x0, ajust_date:0xa4f8, ajust_no:0x1
mod_type1:0x1420, mod_type2:0x352, afe_ptn_id:0xc8c, nsno_l:0x0,
focal_len:0x870, fov_h:0x2328, fov_v:0x1b08,
center_h:0x140, center_v:0xf0,
pixel_pitch:0x230, enable_mode:0x3, tal_mode:0xf, pup_size:7618, check_sum:0xaf22

************************************ EEPROM data file read success, eeprom setting will be used
tl_dev_open: line:700 dev->dev_eeprom.cmn.cam_info.qvga=0 
tl_dev_open: line:715 dev->dev_eeprom.cmn.cam_info.qvga=0 
tl_dev_open: line:716 dev->dev_cap.fmt.width=640 
tl_dev_open: line:717 dev->dev_cap.fmt.height=480 
tl_dev_open: line:718 dev->dev_cap.fmt.pixels=307200 
tl_dev_open: line:719 dev->dev_cap.fmt.size=614400 
enable_mode:3, mode:1
Resolution of output images:
depth : width=640, height=480, stride=1280, bit_per_pixel=16 
ir    : width=640, height=480, stride=1280, bit_per_pixel=16 
bg    : width=0, height=0, stride=0, bit_per_pixel=0 

Mode Info:
mode0 : enable=1, range_near=200, range_far=1200, depth_unit=16, fps=30
mode1 : enable=1, range_near=500, range_far=4500, depth_unit=32, fps=20

Fov Info:
focal_length=2160, angle_h=9000, angle_v=6920

Hardware Info:
PANASONIC TOF CAMERA ADDI9043 MN34906 J6920 
mod_type:0x1420 0x352 afe_ptn_id:0xc8c sno_l:0x0
map_ver:0x3102 sno_u:0x0 ajust_date:0xa4f8 ajust_no:0x1

Lens Info:
sns_h=640, sns_v=480, center_h=320, center_v=240 pixel_pitch=560
planer_prm: -2556331701141 -1588038640561 129826999924473 -1702240300 
distortion_prm: 257950767916435 -1490090541281100 228799137277592 142924586479550 

Camera ID 2 Opened

Press [ctrl + c] to quit. 
freeglut failed to open display ''
[TL_capture:362] 
tl_dev_hal_process_request() failed.
[TL_capture L.347] TL_E_ERR_PARAM
[TL_capture:362] 
tl_dev_hal_process_request() failed.
[TL_capture L.347] TL_E_ERR_PARAM
[TL_capture:362] 
tl_dev_hal_process_request() failed.
[TL_capture L.347] TL_E_ERR_PARAM
Segmentation fault
`

**Comment by keanheong** [comment]
>freeglut failed to open display

Above debug log seem indicate it cannot open a display.

Some point to check:-
a) xWayland is installed successfully in RB5 ?
b) "viewer" is launched under "ssh terminal" or "weston-terminal" ?

Could try below steps ?
1. Connect monitor and keyboard to RB5, log in as root on RB5 (Via RB5 terminal prompt, not via "adb shell" from other PC)
2. Enter cmd [*] to start the xWayland GUI
3. Click the small icon in the upper left corner of the GUI to launch "weston-terminal".
4. Launch "viewer" using "weston-terminal".

[*]
export XDG_RUNTIME_DIR=/usr/bin/weston_socket
export LD_LIBRARY_PATH=/usr/lib:/usr/lib/aarch64-linux-gnu/
export GDK_BACKEND=x11
weston --tty=1 --connector=29 --idle-time=0

**Comment by akash901** [comment]
@keanheong Thank you for responding.

> Could try below steps ?

> Connect monitor and keyboard to RB5, log in as root on RB5 (Via RB5 terminal prompt, not via "adb shell" from other PC)
> Enter cmd [*] to start the xWayland GUI
> Click the small icon in the upper left corner of the GUI to launch "weston-terminal".
> Launch "viewer" using "weston-terminal".
> [*]
> export XDG_RUNTIME_DIR=/usr/bin/weston_socket
> export LD_LIBRARY_PATH=/usr/lib:/usr/lib/aarch64-linux-gnu/
> export GDK_BACKEND=x11
> weston --tty=1 --connector=29 --idle-time=0

I did follow above mentioned steps and xwayland was also installed on RB5. But stills I am facing error as shown in below snapshot. It is still unable to open display.

![WhatsApp Image 2022-04-11 at 10 34 39 AM](https://user-images.githubusercontent.com/76035798/162668571-c1146cba-1696-4ec5-bb15-7e14a2d2bf48.jpeg)

Is anything I am missing? Thundercomm's document also provides some Tof image(sample app and .so file) which I havent loaded on RB5 yet. Is there any external dependency apart from this package to be installed?

**Comment by keanheong** [comment]
> Thundercomm's document also provides some Tof image(sample app and .so file) which I haven't loaded on RB5 yet

Thundercomm's sample apps is a basic app that able to save image from ToF into file (no streaming).
It is good to try run it, so that it ensure the .so file is working well.
(It can run at ssh terminal, without any xWayland GUI. View the saved image offline in other PC to verify)

For viewer app, it seem we still see "freeglut failed to open display".
-Cmd "export GDK_BACKEND=x11" is already executed successfully before xWayland GUI run ? 
-Issue cmd  "echo $DISPLAY" give any display number ?
-"weston.ini" and "symlink to xwayland lib" is OK as stated in https://github.com/OpenNuvoton/ToF-viewer-app-for-Qualcomm-RB5/blob/master/viewer/ReadMe.txt ?

**Comment by akash901** [comment]
> For viewer app, it seem we still see "freeglut failed to open display".
> -Cmd "export GDK_BACKEND=x11" is already executed successfully before xWayland GUI run ?
> -Issue cmd "echo $DISPLAY" give any display number ?
> -"weston.ini" and "symlink to xwayland lib" is OK as stated in https://github.com/OpenNuvoton/ToF-viewer-app-for-Qualcomm-RB5/blob/master/viewer/ReadMe.txt ?

@keanheong Yes all these above environment variables and symlink is done and its present in my bashrc file as well. I still see "freeglut failed to open display" error. Need further help in debugging this issue.

**Comment by keanheong** [comment]
>freeglut failed to open display

Issue cmd "echo $DISPLAY" give any display number ?


>above environment variables and symlink is done and its present in my bashrc file as well.

Shall we troubleshoot by remove env variable setting in bashrc file first ? And key in cmd as sequence stated in ReadMe.txt
(As the sequence of cmd seem affect the outcome as in our last trial, especially the cmd "export GDK_BACKEND=x11")


>It is good to try run it, so that it ensure the .so file is working well.

Have you try Thundercomm's sample app and you can get image saved in some folder ?
(To check basic ToF .so is work well...)

**Comment by akash901** [comment]
@keanheong Please find answers below.

> Issue cmd "echo $DISPLAY" give any display number ?

No it is not giving any number. DISPLAY variable is not set to any number in my environment.

> Shall we troubleshoot by remove env variable setting in bashrc file first ? And key in cmd as sequence stated in ReadMe.txt
> (As the sequence of cmd seem affect the outcome as in our last trial, especially the cmd "export GDK_BACKEND=x11")

Yes I followed the same procedure as that in README for setting all environment variables as well but still getting same error as above.

> Have you try Thundercomm's sample app and you can get image saved in some folder ?
> (To check basic ToF .so is work well...)

Yes I tried thundercomm testapp but it is also giving segmentation fault and image is not been saved.
Please check below shown logs. I extracted rb5-postcs-camera-tof-images-20210322.tar.gz file from thundercomm documents page for RB5 to test this testapp.

Error logs : 
> sh-4.4# testapp 
> -------------------------TOF----------------------------
> 
> Image type:
> 0 : TL_E_IMAGE_TYPE_VGA_DEPTH_QVGA_IR_BG
> 1 : TL_E_IMAGE_TYPE_QVGA_DEPTH_IR_BG
> 2 : TL_E_IMAGE_TYPE_VGA_DEPTH_IR
> 3 : TL_E_IMAGE_TYPE_VGA_IR_QVGA_DEPTH
> 4 : TL_E_IMAGE_TYPE_VGA_IR_BG
> Enter: 2
> 
> Mode method:
> 0 : MODE0
> 1 : MODE1
> Enter: 1
> 
> Save frame number:
> Enter: 1
> 
> 
> Number of camera:3
> 0: facing:1, orien:270, version:773, cost:100, conflict_length:0
> 1: facing:2, orien:270, version:773, cost:100, conflict_length:0
> 2: facing:1, orien:180, version:773, cost:100, conflict_length:0(TOF)
> 
> Resolution of output images:
> depth : width=640, height=480, stride=1280, bit_per_pixel=16 
> ir    : width=640, height=480, stride=1280, bit_per_pixel=16 
> bg    : width=0, height=0, stride=0, bit_per_pixel=0 
> 
> 
> Camera ID 2 Opened
> 
> tl_dev_eeprom_read_cmn_mode: new p_cmn_mode:0x5594043740, size:2160 E
> 
> mod_name:PANASONIC TOF CAMERA, afe_name:ADDI9043, sns_name:MN34906, lns_name:J6920
> map_ver:0x3102, sno_u:0x0, ajust_date:0xa4f8, ajust_no:0x1
> mod_type1:0x1420, mod_type2:0x352, afe_ptn_id:0xc8c, nsno_l:0x0,
> focal_len:0x870, fov_h:0x2328, fov_v:0x1b08,
> center_h:0x140, center_v:0xf0,
> pixel_pitch:0x230, enable_mode:0x3, tal_mode:0xf, pup_size:7618, check_sum:0xab2b
> 
> 
> ************************************ EEPROM data file read success, eeprom setting will be used
> 
> 
> Mode Info:
> mode0 : enable=1, range_near=200, range_far=1200, depth_unit=16, fps=30
> mode1 : enable=1, range_near=500, range_far=4500, depth_unit=32, fps=20
> 
> 
> Fov Info:
> focal_length=2160, angle_h=9000, angle_v=6920
> 
> 
> Hardware Info:
> PANASONIC TOF CAMERA ADDI9043 MN34906 J6920 
> mod_type:0x1420 0x352 afe_ptn_id:0xc8c sno_l:0x0
> map_ver:0x3102 sno_u:0x0 ajust_date:0xa4f8 ajust_no:0x1
> 
> Segmentation fault

**Comment by keanheong** [comment]
>No it is not giving any number. DISPLAY variable is not set to any number in my environment.

It need to be at least have output like ":0" which indicate some display number.

It is observed that your screenshot of xWayland bit different (No gray wallpaper and topbar icon).
a) if issue cmd "env", do we find env variable such as HOME, DISPLAY etc ?
b) Cmd below to activte xWayland :-
```
export XDG_RUNTIME_DIR=/usr/bin/weston_socket
export LD_LIBRARY_PATH=/usr/lib:/usr/lib/aarch64-linux-gnu/
export GDK_BACKEND=x11
weston --tty=1 --connector=29 --idle-time=0
```
Above cmd is issue at "adb shell" or "RB5 terminal" ? (Observed that if it is issue via "adb shell", there will be no env variable such as HOME, DISPLAY...)
c) Content of "weston.ini" is correct ? (Default editor in RB5 seem make us make some mistake in this file too)

>thundercomm testapp but it is also giving segmentation fault

Think the proper driver (*.so/*.bin) not yet setup successfully in your RB5 set.
Please get further support from TC so that at least the "testapp" basic functionality is able to run in RB5.
"viewer" app only enhance it by render it to GUI window under xWayland GUI using OpenCV/OpenGL.

**Comment by akash901** [comment]
@keanheong Thank you for complete support. I had to reflash RB5 system image and then ran testapp with support from Thundercomm. It worked and then I tried this viewer as well. Now I am able to get point cloud view, IR image and color image as well.

On seperate note, Are there any plans of Nuvoton to develop ROS driver for this camera?

**Comment by keanheong** [comment]
>Now I am able to get point cloud view, IR image and color image as well.

Glad to hear that all work well in your new setup ....


>On separate note, Are there any plans of Nuvoton to develop ROS driver for this camera?

There are working ROS driver for this camera, but not publish yet as we still not satisfies with its maturity (yet need more improvement).

**Comment by keanheong** [comment]
Hereby closed as it work well in new setup.
